mapplic.settings:
  type: mapping
  label: Settings
  mapping:
    mapplic_height:
      type: integer
    mapplic_sidebar:
      type: boolean
    mapplic_mapfill:
      type: boolean
    mapplic_zoombuttons:
      type: boolean
    mapplic_clearbutton:
      type: boolean
    mapplic_minimap:
      type: boolean
    mapplic_locations:
      type: boolean
    mapplic_fullscreen:
      type: boolean
    mapplic_hovertip:
      type: boolean
    mapplic_search:
      type: boolean
    mapplic_animate:
      type: boolean
    mapplic_developer_mode:
      type: boolean
    mapplic_zoom:
      type: boolean
    mapplic_max_scale:
      type: integer
    mapplic_map_height:
      type: integer
    mapplic_map_width:
      type: integer
